package constants

import "fmt"

const (
	_PEER_REQUEST    = "==PEER==REQUEST"
	_PEER_ACCEPTED   = "==PEER==ACCEPTED"
	_START_BRIDGE    = "==START==BRIDGE"
	_BRIDGE_REJECTED = "==BRIDGE==REJECTED"
	_BRIDGE_ACCEPTED = "==BRIDGE==ACCEPTED"
	_TUNNEL_REQUEST  = "==TUNNEL==REQUEST"
	_TUNNEL_ACCEPTED = "==TUNNEL==ACCEPTED"
	_TUNNEL_REJECTED = "==TUNNEL==REJECTED"
	_KEEP_ALIVE      = "==KEEP==ALIVE"
)
const MAX_PEER_QUOTA = 10
const VERSION_MAJOR byte = 0
const VERSION_MINOR byte = 1

var prefix = fmt.Sprintln("TCPRP", VERSION_MAJOR, VERSION_MINOR)
